# Generated by Django 4.0.1 on 2022-01-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_completed',
            new_name='is_finished',
        ),
    ]
